In [114]:
import pandas as pd
import numpy as np


In [115]:
df=pd.read_csv("Crop_recommendation.csv")

In [116]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [117]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

## Classes for crops 
        ['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee']

In [118]:
df['label'].value_counts()

label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

In [119]:
X=df.drop(['label'],axis=1)

In [120]:
X

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [121]:
Y=df['label']

In [122]:
Y

0         rice
1         rice
2         rice
3         rice
4         rice
         ...  
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [123]:
from sklearn.model_selection import train_test_split
X_train,x_test,Y_train,y_test=train_test_split(X,Y,random_state=42,test_size=0.25)

In [124]:
X_train

N    P    K  temperature   humidity        ph    rainfall
564    22   36   16    30.581395  50.771481  8.184229   64.585596
916    18   27   41    22.365094  92.308824  7.175344  104.821633
1700   61   68   50    35.214628  91.497251  6.793245  243.074507
436    26   72   22    28.767949  37.577921  4.674942   91.720849
1555    2  140  197    22.697801  92.822234  5.534567  105.050823
...   ...  ...  ...          ...        ...       ...         ...
1638   10    5    5    21.213070  91.353492  7.817846  112.983436
1095  108   94   47    27.359116  84.546250  6.387431   90.812505
1130   11   36   31    27.920633  51.779659  6.475449  100.258567
1294   11  124  204    13.429886  80.066340  6.361141   71.400430
860    32   78   22    23.970814  62.355576  7.007038   53.409060

[1650 rows x 7 columns]

In [125]:
y_test

1451     muskmelon
1334    watermelon
1761        papaya
1735        papaya
1576         apple
           ...    
2119        coffee
1756        papaya
294       chickpea
2183        coffee
2093          jute
Name: label, Length: 550, dtype: object

In [126]:
from sklearn.preprocessing import StandardScaler
ssc=StandardScaler()
X_train=ssc.fit_transform(X_train)
x_test=ssc.transform(x_test)

In [127]:
X_train

array([[-7.74026344e-01, -5.22604462e-01, -6.28724908e-01, ...,
        -9.51256909e-01,  2.19982609e+00, -6.86012983e-01],
       [-8.81256962e-01, -7.93767155e-01, -1.37942559e-01, ...,
         9.39856699e-01,  9.02028907e-01,  4.18192366e-02],
       [ 2.71472181e-01,  4.41529556e-01,  3.87390868e-02, ...,
         9.02907360e-01,  4.10508789e-01,  2.54268422e+00],
       ...,
       [-1.06891054e+00, -5.22604462e-01, -3.34255499e-01, ...,
        -9.05356554e-01,  1.70580458e-03, -4.07223532e-02],
       [-1.06891054e+00,  2.12876409e+00,  3.06195836e+00, ...,
         3.82480441e-01, -1.45336714e-01, -5.62739020e-01],
       [-5.05949799e-01,  7.42821437e-01, -5.10937144e-01, ...,
        -4.23855858e-01,  6.85524273e-01, -8.88186049e-01]])

In [128]:
x_test

array([[ 1.34377836, -1.09505904, -0.0201548 , ...,  1.05007959,
        -0.37185066, -1.37841507],
       [ 1.2633554 , -1.36622173,  0.05837038, ...,  0.67642042,
        -0.27629569, -0.9601543 ],
       [ 0.21785687,  0.26075443,  0.01910779, ...,  0.98734665,
         0.60121475,  0.22192187],
       ...,
       [-0.55956511,  0.35114199,  0.66694049, ..., -2.56719443,
         0.80999403, -0.46544778],
       [ 1.12931713, -0.82389634, -0.41278067, ..., -0.69189211,
         1.04721835,  0.63663777],
       [ 0.32508749, -0.19118339, -0.25573032, ...,  0.7917565 ,
         1.23317088,  1.65276317]])

In [129]:
y_test

1451     muskmelon
1334    watermelon
1761        papaya
1735        papaya
1576         apple
           ...    
2119        coffee
1756        papaya
294       chickpea
2183        coffee
2093          jute
Name: label, Length: 550, dtype: object

In [130]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
Y_train=pd.Series(Y_train)
lr.fit(X_train,Y_train)

LogisticRegression()

In [131]:
y_pred=lr.predict(x_test)

In [136]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.96

Confusion Matrix:
 [[29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0 24  0  0  0  0  0  0  0  0  1  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 24  0  0  0  0  1  0  0  0]

In [134]:
y_pred

array(['muskmelon', 'watermelon', 'papaya', 'papaya', 'apple', 'mango',
       'apple', 'mothbeans', 'mungbean', 'lentil', 'blackgram', 'coconut',
       'pomegranate', 'jute', 'coconut', 'pomegranate', 'apple', 'maize',
       'papaya', 'muskmelon', 'coffee', 'papaya', 'orange', 'papaya',
       'chickpea', 'jute', 'mungbean', 'orange', 'pigeonpeas', 'rice',
       'pomegranate', 'mothbeans', 'jute', 'lentil', 'jute', 'blackgram',
       'jute', 'chickpea', 'chickpea', 'kidneybeans', 'papaya', 'mango',
       'blackgram', 'maize', 'mungbean', 'maize', 'pigeonpeas', 'coconut',
       'muskmelon', 'maize', 'blackgram', 'coffee', 'grapes', 'mungbean',
       'coffee', 'kidneybeans', 'cotton', 'apple', 'banana', 'lentil',
       'watermelon', 'coconut', 'lentil', 'orange', 'papaya', 'blackgram',
       'orange', 'rice', 'muskmelon', 'pigeonpeas', 'muskmelon',
       'coconut', 'jute', 'banana', 'blackgram', 'papaya', 'banana',
       'cotton', 'watermelon', 'orange', 'coffee', 'chickpea',

# Dumping model and Standard scalar

In [139]:
import pickle
pickle.dump(lr,open("Crop_classification_model.pkl","wb"))

In [141]:
pickle.dump(ssc,open("Crop_Standard_Scalar.pkl","wb"))